
KEYWORD(ORG,		MERLIN | DASM | IIGS)
KEYWORD(EQU,		MERLIN | DASM | IIGS)
KEYWORD(ERR,		MERLIN | DASM		)	// MERLIN

KEYWORD(PUT,		MERLIN				)	// MERLIN	----	----
KEYWORD(USE,		MERLIN				)	// MERLIN	----	----
KEYWORD(INCLUDE,			 DASM		)	// ------	DASM	????
KEYWORD(SAV,		MERLIN				)	// MERLIN	????	????
KEYWORD(DSK,		MERLIN				)	// MERLIN	????	????

KEYWORD(MAC,		MERLIN | DASM		)	// MERLIN	????	????
KEYWORD(EOM,		MERLIN				)	// MERLIN	????	????
KEYWORD(ENDM,				 DASM		)	// ------	DASM	????
KEYWORD(SEG,				 DASM		)	// ------	DASM	????
KEYWORD(DUM,		MERLIN				)	// MERLIN
KEYWORD(DUMMY,		MERLIN				)	// MERLIN
KEYWORD(DEND,		MERLIN				)	// MERLIN
KEYWORD(USR,		MERLIN				)	// MERLIN

KEYWORD(LUP,		MERLIN				)	// MERLIN	----	????
KEYWORD(REPEAT,				 DASM		)	// ------	DASM	????
KEYWORD(REPEND,				 DASM		)	// ------	DASM	????

KEYWORD(DB,			MERLIN				)
KEYWORD(DFB,		MERLIN				)
KEYWORD(DDB,		MERLIN				)
KEYWORD(DW,			MERLIN				)
KEYWORD(DA,			MERLIN				)
KEYWORD(DS,			MERLIN | DASM		)
KEYWORD(HEX,		MERLIN | DASM		)
KEYWORD(DC,					 DASM | IIGS)
KEYWORD(BYTE,				 DASM		)
KEYWORD(WORD,				 DASM		)
KEYWORD(ALIGN,				 DASM		)
KEYWORD(ASC,		MERLIN				)

KEYWORD(DO,			MERLIN				)	// MERLIN	----	----
KEYWORD(ELSE,		MERLIN | DASM | IIGS)	// MERLIN	DASM	IIGS
KEYWORD(FIN,		MERLIN				)	// MERLIN	----	----
KEYWORD(IF,					 DASM | IIGS)	// ------	DASM	IIGS
KEYWORD(THEN,				 DASM | IIGS)	// ------	----	IIGS
KEYWORD(ELIF,				 DASM		)	// ------	DASM	IIGS
KEYWORD(ENDIF,				 DASM | IIGS)	// ------	DASM	IIGS

KEYWORD(TR,			MERLIN				)	// MERLIN	----	----
KEYWORD(LST,		MERLIN				)	// MERLIN	----	----
KEYWORD(LSTDO,		MERLIN				)	// MERLIN	----	----
KEYWORD(EXP,		MERLIN				)	// MERLIN	----	----
KEYWORD(ON,			MERLIN				)	// MERLIN	----	----
KEYWORD(OFF,		MERLIN				)	// MERLIN	----	----
KEYWORD(PAGE,		MERLIN				)	// MERLIN	----	----

KEYWORD(MACHINE,					IIGS)	// ------	----	IIGS
KEYWORD(PROCESSOR,			 DASM		)	// ------	DASM
KEYWORD(SUBROUTINE,			 DASM		)	// ------	DASM

#undef KEYWORD
