
* generate picture index equates

                DUMMY $00
pAIR_SWIMMER    DS  1
pARMOR_ALIEN    DS  1
pBARACKADER     DS  1
pBIRD_INSECT    DS  1
pBLOW_DART      DS  1
pBTWN_LEGS      DS  1
pCEIL_SWINGER   DS  1
pCEILING_FAN    DS  1
pCLAPPER        DS  1
pCLUBBER        DS  1
pCROSS_BOW      DS  1
pFINGERS        DS  1
pFROG_BOT       DS  1
pGAS_CLOUD      DS  1
pHANGING_BOT    DS  1
pHOLSTER        DS  1
pHORNED_DOG     DS  1
pLITTLE_BUG     DS  1
pOILER          DS  1
pONE_EYE        DS  1
pPARTICLE_MAN   DS  1
pPEEKER         DS  1
pPER_ALIEN      DS  1
pPINK_WINGS     DS  1
pPLATFORM       DS  1
pPROBOT         DS  1
pRAG_ALIEN      DS  1
pROBIEN         DS  1
pROBOT          DS  1
pRUUIKS_MEN     DS  1
pSHIELD         DS  1
pSIX_ARM        DS  1
pSLEEPY         DS  1
pSPACE_MAN      DS  1
pSPACE_SHIP     DS  1
pSQUINTER       DS  1
pSTARBURST      DS  1
pSTICKY         DS  1
pSTINKY         DS  1
pSTRINGY_HAND   DS  1
pTREE_ALIEN     DS  1
pTRUNK          DS  1
pTWISTER        DS  1
pWIERD_ALIEN    DS  1
pWORMS          DS  1
                DEND
