
* generate picture index equates

                DUMMY $00
pACID_SPITTER   DS  1
pATOM_SHIFTER   DS  1
pCARNIVORE      DS  1
pCLOAKD_ALIEN   DS  1
pCYLINDER_BOT   DS  1
pDIODE_ROBOT    DS  1
pEXPLODE        DS  1
pFAKER          DS  1
pGLASS_GUY      DS  1
pGREEN_PUDDLE   DS  1
pINSECT2        DS  1               ;Duplicated
pLITTLE_MEN     DS  1
pMAGNET         DS  1
pMISER          DS  1
pPHASOID        DS  1
pPROG_CHANGER   DS  1
pROBED_SELLER   DS  1
pSCREAMER       DS  1
pSEVEN_CLAWS    DS  1
pSHARP_SHOOTR   DS  1
pSPARKLES       DS  1
pTAILFIGHTER    DS  1
pTANGIBLE_GAS   DS  1
pTF_BAIT        DS  1
pTREE_HANGER    DS  1
pWEB_THING      DS  1
                DEND
