
* generate picture index equates

                DUMMY $00
pBRANCHES       DS  1
pCEILING_FAN    DS  1
pCONSTRICTOR    DS  1
pDIZZY          DS  1
pFIRE_MAN       DS  1
pFURNACE        DS  1
pIN_WEB         DS  1
pINSECT1        DS  1
pLEASHED_DOGS   DS  1
pLITTL_PLANES   DS  1
pLIZARD         DS  1
pLONG_ARM       DS  1
pMETAL_MITES    DS  1
pOMEBA          DS  1
pPLATFORM       DS  1
pPOINTY_HEAD    DS  1
pRAG_ALIEN      DS  1
pREPAIR_UNIT    DS  1
pROBIEN         DS  1
pSCAVENGER      DS  1
pSIX_ARM        DS  1
pSLICER         DS  1
pSNOUT          DS  1
pSNOW_JOB       DS  1
pSPOOL_ALIEN    DS  1
pSPOOR_PLANT    DS  1
pSTAFF          DS  1
pSTICKY         DS  1
pSTRINGY_HAND   DS  1
pTENTICLE       DS  1
pTREADED_BOT    DS  1
pTWISTER        DS  1
pUNLOADER       DS  1
pWATER_TOWER    DS  1
                DEND
