
* generate picture index equates

                DUMMY $00
pAIRLOCK        DS  1
pANTISIPATOR    DS  1
pBLACK_ALIEN    DS  1
pCORE_ALIEN     DS  1
pFOUR_SWORDS    DS  1
pGODZILLA       DS  1
pGREEN_HEAD     DS  1
pINFORMER       DS  1
pINVERSE        DS  1
pONE_ARM_BLOB   DS  1
pRABBIT_EARS    DS  1
pRICOCHET       DS  1
pRUNNING_BOT    DS  1
pTANK_HUMAN     DS  1
pTELEPORTER     DS  1
pTHROWER        DS  1
pTIME_WARP      DS  1
                DEND
