
* generate picture index equates

                DUMMY $00
pALIEN_ON       DS  1
pCENTAUR        DS  1
pCOOLER         DS  1
pDRILLER        DS  1
pDUAL_HEAD      DS  1
pEARS           DS  1
pFUNGUS         DS  1
pGLOWER         DS  1
pGREMLIN        DS  1
pHEATER         DS  1
pHOT_HEAD       DS  1
pINSECT         DS  1
pINVISIBLE      DS  1
pKAMAKAZE       DS  1
pLIGHT_ALIEN    DS  1
pPOISON_SUIT    DS  1
pPUNKER         DS  1
pQUEEN_INSECT   DS  1
pREFLEX_ALIEN   DS  1
pSHIFTER        DS  1
pSWAMP_THING    DS  1
pWANDERING      DS  1
pWIND_TUNNEL    DS  1
                DEND
