FACE_1			=	%00100000
FACE_2			=	%00010000
FACE_3			=	%00001000
FACE_4			=	%00000100
FACE_5			=	%00000010
FACE_6			=	%00000001

ALL_FACES		=	FACE_1+FACE_2+FACE_3+FACE_4+FACE_5+FACE_6

UNKNOWN_ALIEN	=	%00000000
ALIEN_FORM		=	%01000000
ROBOT_FORM		=	%10000000
UNKNOWN_ROBOT	=	%11000000

animated		=	%11100000		;Also in /FIGHT/LOADER/EQUATES
notcompiled		=	%00000000
iscompiled		=	%00001000
frame0			=	0
frame1			=	1
frame3			=	3

attack			=	0
blink			=	1
kill			=	2
damage			=	3
move			=	4

uparound		=	0
updown			=	1
upstop			=	2
special			=	15

repeat0			=	0
repeat1			=	1
repeat2			=	2

normalspeed		=	8
