BLOCK_LIST		DW	BLOCK_00
				DW	BLOCK_10
				DW	BLOCK_20
				DW	BLOCK_30
				DW	BLOCK_40
				DW	BLOCK_50
				DW	BLOCK_60
				DW	BLOCK_70
				DW	BLOCK_80
				DW	BLOCK_90
				DW	BLOCK_A0
				DW	BLOCK_B0
				DW	0
				DW	0
				DW	BLOCK_E0


BLOCK_00
				USR	(SWINGS)=
				USR	(STRIKES)=
				USR	(POKES)=
				USR	(SCRATCHES)=
				USR	(CLAWS)=
				USR	(STABS)=
				USR	(THRUSTS)=
				USR	(HACKS)=
				USR	(SLASHES)=
				USR	(BITES)=
				USR	(SNIPS)=
				USR	(PUNCHES)=
				USR	(GRABS)=
				USR	(REACHES)=
				USR	(KICKES)=
				USR	(WHIPS)=

BLOCK_10
				USR	(SWOOPS)=
				USR	(SPRAYS)=
				USR	(LUNGES)=
				USR	(JUMPS)=
				USR	(AS)=
				USR	(TO)=
				USR	(THE)=
				USR	(HIT)=
				USR	(GRENADE)=
				USR	(EXPLODES)=
				USR	(SONIC)=
				USR	(BURNED)=
				USR	(BLINDED)=
				USR	(GYRO)=
				USR	(TOWARD)=
				USR	(ARCS)=

BLOCK_20
				USR	(BOOMERANG)=
				USR	(BEING)=
				USR	(ANYTHING)=
				USR	(CUTS)=
				USR	(SCANS)=
				USR	(FAILS)=
				USR	(IDENTIFY)=
				USR	(IDENTIFIES)=
				USR	(SLICES)=
				USR	(DOESN'T)=
				USR	(THRASHES)=
				USR	(SWIPES)=
				USR	(TRANSMIT)=
				USR	(TRANSMITS)=
				USR	(SWING)=
				USR	(CRACKS)=

BLOCK_30
				USR	(AND)=
				USR	(FOR)=
				USR	(NOTHING)=
				USR	(INFLICTS)=		;|
				USR	(CAUSES)=		;|
				USR	(CONNECTS)=		;|
				USR	(HITS)=			;|
				USR	(DAMAGE)=
				USR	(IS)=
				USR	(KILLED)=		;|
				USR	(DESTROYED)=	;|
				USR	(FIRE)=			;  |
				USR	(SHOOT)=		;  |
				USR	(BLAST)=		;  |
				USR	(SHOT)=			;  |
				USR	(MISSES)=		;|
									;|
BLOCK_40							;|
				USR	(WHIZZES)=		;|
				USR	(FLIES)=		;|
				USR	(BUZZES)=		;|
				USR	(WITH)=
				USR	(BUT)=
				USR	(IT)=
				USR	(RICOCHETS)=
				USR	(PAST)=
				USR	(ATTACKER)=
				USR	(BRAIN)=
				USR	(JAMMING)=
				USR	(WAVES)=
				USR	(WIDE)=
				USR	(VIBRATE)=
				USR	(OF)=
				USR	(UNLOADS)=

BLOCK_50
				USR	(SEEM)=
				USR	(HAVE)=
				USR	(WEAK)=
				USR	(HARMLESS)=
				USR	(UNIT)=
				USR	(LETS_LOOSE)=
				USR	(THROWS)=
				USR	(DISCHARGES)=
				USR	(RELEASES)=
				USR	(EMITS)=
				USR	(SCORCHING)=	;|
				USR	(BURNING)=		;|
				USR	(SEARING)=		;|
				USR	(CRACKLING)=	;   |
				USR	(PULSATING)=	;   |
				USR	(GLOWING)=		;   |
									;   |
BLOCK_60							;   |
				USR	(BRILLIANT)=	;   |
				USR	(BLINDING)=		;   |
				USR	(GLARING)=		;   |
				USR	(BOLT)=
				USR	(FLASH)=
				USR	(ENERGY)=
				USR	(RUNS)=
				USR	(OUT)=
				USR	(BLOCKED)=
				USR	(INTERCEPTED)=
				USR	(WALL)=
				USR	(STARTS)=
				USR	(EFFECT)=
				USR	(STOPS)=
				USR	(ABRUPTLY)=
				USR	(IN)=

BLOCK_70
				USR	(WAY)=
				USR	(NO)=
				USR	(ONE)=
				USR	(AFFECTED)=
				USR	(THAT)=
				USR	(EVERYBODY)=
				USR	(SO)=
				USR	(OFF)=
				USR	(IT'S)=
				USR	(RESTRAINING)=
				USR	(MESSAGE)=
				USR	(ABSORBED)=
				USR	(BY)=
				USR	(INTO)=
				USR	(REMAINS)=
				USR	(DODGES)=		;|
									;|
BLOCK_80							;|
				USR	(DUCKS)=		;|
				USR	(EVADES)=		;|
				USR	(AVOIDS)=		;|
				USR	(BLOCKS)=
				USR	(ATTACK)=
				USR	(DAMAGED)=		;|
				USR	(INJURED)=		;|
				USR	(HARMED)=		;|
				USR	(GOES)=
				USR	(ISN'T)=
				USR	(QUICK)=
				USR	(ENOUGH)=
				USR	(THIN_AIR)=					;|
				USR	(NOBODY)=					;|
				USR	(AN_EMPTY_SQUARE)=		;|
				USR	(DEFLECTED)=

BLOCK_90
				USR	(BADLY)=
				USR	(BLOW)=
				USR	(RECEIVED)=
				USR	(ANYONE)=
				USR	(IGNORED)=
				USR	(OBEYED)=
				USR	(POWERFUL)=		;|
				USR	(DEVASTATING)=	;|
				USR	(DESTRUCTIVE)=	;|
				USR	(UNKNOWN)=		;   |
				USR	(ALIEN)=		;   |
				USR	(ROBOT)=		;   |
				USR	(EXCHANGES)=
				USR	(EQUIPMENT)=
				USR	(HEALS)=		;|
				USR	(REPAIRS)=		;|

BLOCK_A0
				USR	(LONGER)=
				USR	(SNIFFS)=
				USR	(MUSCLE)=		;|
				USR	(REFLEX)=		;|
				USR	(DIES)=
				USR	(INSTANTLY)=
				USR	(NOT)=
				USR	(RETURNS)=
				USR	(A)=
				USR	(AT)=
				USR	(AN)=
				USR	(STRIKE)=
				USR	(DETONATE)=
				USR	(CRASHES)=
				USR	(FLOOR)=
				USR	(DOES)=

BLOCK_B0
				USR	(GIVES)=
				USR	(RETREAT)=
				USR	(SIGNAL)=
				USR	(ACTIVATE)=
				USR	(ENVELOPS)=
				USR	(IMMOBILIZER)=
				USR	(IMMOBILIZE)=
				USR	(SEND)=
				USR	(SENDS)=
				USR	(HAS)=
				USR	(CRITICAL)=
				USR	(BROKEN)=
				USR	(IMMOBILE)=
				USR	(RESTRAINED)=
				USR	(JAMMED)=
				USR	(X)=			;*


*** THESE ARE USED IN RUN RESOLVER CODE
BLOCK_E0
				USR	(GROUP)=
				USR	(ALIENS)=
				USR	(SUCCESSFULLY)=
				USR	(ATTEMPT)=
				USR	(UNSUCCESSFUL)=
				USR	(RETREATED)=
