TABLE2			DB	$FF,$FF,$FF
				DB	$FF
TABLE4			DB	$FF,$FF,$FF
				DB	$FF
LINTABL			DB	$FF,$FF,$FF
				DB	$FF,$FF,$FF
				DB	$FF,$FF,$FF
				DB	$FF,$FF,$FF
				DB	$FF,$FF,$FF
				DB	$FF,$FF,$FF
CURTABL			DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00
VISIBLE			DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00
MINTABL			DB	$00,$00,$00
FORMED			DB	$00,$00,$00
				DB	$00

THE_PRICE		DS	4
REMAINS			DS	4
OPEN_SLOT		DS	1				;Destination of bought equipment
STATUS			DS	1
STCKDIF			DS	1
