HALL			DFB	$00,$00,$1C
				DFB	$01,$0A,$1C
				DFB	$FE
				DFB	$00,$12,$00
				DFB	$00,$12,$5D
				DFB	$FE
				DFB	$00,$2F,$00
				DFB	$00,$2F,$5D
				DFB	$FE
				DFB	$01,$0A,$1B	
				DFB	$01,$10,$00
				DFB	$FE
				DFB	$01,$0A,$1D	
				DFB	$01,$17,$5D
				DFB	$FE	
				DFB	$00,$4D,$73
				DFB	$00,$F5,$73
				DFB	$FE
				DFB	$00,$4D,$7B
				DFB	$00,$F5,$7B
				DFB	$FF

BBORDER			DFB	$00,$4D,$75
				DFB	$00,$F5,$75
				DFB	$FF

OLINE			DFB	$00,$00,$5F
				DFB	$01,$17,$5F
				DFB	$FF

REMOVER			DFB	$00,$4A,$08
				DFB	$01,$02,$08
				DFB	$FF

ADDER			DFB	$00,$50,$0D
				DFB	$00,$D8,$0D
				DFB	$FE
				DFB	$00,$50,$74
				DFB	$00,$D8,$74
				DFB	$FF
