AA				USR	(VEGAN_WARRIOR___)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$03
				DB	$A3,$22,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$37,$CC,$FA,$DD,$01,$0F
				DB	$FF

				DB	$23,$00			;tview dimens, offset
				DB	$80
				DB	$00,$00,$00
				DB	$00,$00,$06
				DB	$03
				DB	$00,$73,$76
				DB	$06,$78,$7E
				DB	$7F
				DB	$20,$67,$67
				DB	$30,$0F,$3F
				DB	$7F
				DB	$3F,$7B,$73
				DB	$0B,$1A,$30
				DB	$00
				DB	$7E,$6F,$67
				DB	$68,$26,$06
				DB	$0C
				DB	$FF				;tview end mark

BB				USR	("OILER"_________)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$AA,$9D,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$46,$CC,$F6,$DD,$02
				DB	$0F,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$60,$76,$4F
				DB	$36,$38,$1C
				DB	$0E
				DB	$03,$37,$7F
				DB	$37,$03,$00
				DB	$00
				DB	$38,$60,$00
				DB	$00,$00,$00
				DB	$00
				DB	$00,$01,$07
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

CC				USR	("SNOOZER"_______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$D9,$AE,$02
				DB	$A6,$2A,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$37,$CC,$F7,$F8,$CC,$FE
				DB	$DD,$01,$04,$0F,$FF

				DB	$23,$00			;tview dimens, offset
				DB	$40,$40,$40
				DB	$70,$7C,$7E
				DB	$7E
				DB	$01,$01,$01
				DB	$07,$1F,$3F
				DB	$3F
				DB	$7E,$0C,$73
				DB	$76,$60,$00
				DB	$40
				DB	$3F,$18,$67
				DB	$37,$03,$00
				DB	$03
				DB	$00,$40,$00
				DB	$60,$00,$60
				DB	$30
				DB	$00,$03,$00
				DB	$01,$00,$03
				DB	$06
				DB	$FF				;tview end mark

DD				USR	(MPC9_ROBOT______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$C0,$24,$00
				DB	$AA,$AA,$00
				DB	$00,$00,$00
				DB	$52,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$16,$CC,$28,$3A,$DD,$01
				DB	$03,$FF

				DB	$52,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$00,$70
				DB	$5C
				DB	$60,$70,$18
				DB	$7C,$78,$30
				DB	$6B
				DB	$07,$0F,$1F
				DB	$33,$1F,$0E
				DB	$57
				DB	$00,$00,$00
				DB	$00,$00,$0E
				DB	$3B
				DB	$80
				DB	$0E,$1B,$33
				DB	$00,$00,$00
				DB	$00
				DB	$1E,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$78,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$70,$58,$4C
				DB	$00,$00,$00
				DB	$00
				DB	$00,$01,$01
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

EE				USR	(AIMTAK_AMPHIBIAN)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$02
				DB	$AB,$26,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$29,$49,$CC,$FF
				DB	$DD,$01,$02,$0F,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$60,$78,$7C
				DB	$6E,$78,$44
				DB	$4E
				DB	$01,$07,$0F
				DB	$1D,$07,$18
				DB	$18
				DB	$46,$40,$40
				DB	$00,$00,$00
				DB	$00
				DB	$0E,$03,$00
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

FF				USR	("AIR_SWIMMER"___)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$02
				DB	$AA,$1A,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$DD,$01,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$00,$40,$00
				DB	$60,$78,$5C
				DB	$7C
				DB	$03,$03,$00
				DB	$07,$1F,$3B
				DB	$3F
				DB	$0C,$0C,$08
				DB	$00,$00,$00
				DB	$00
				DB	$30,$30,$10
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

GG				USR	(POISONOUS_PEST__)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$01
				DB	$A6,$2E,$00
				DB	$00,$00,$00
				DB	$21,$02
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$F8,$F9,$DD,$01
				DB	$07,$FF

				DB	animated+notcompiled+frame0
				DB	$11
				BYTE	damage;upstop
				BYTE	repeat0;normalspeed

				DB	$22,$02
				DB	$18,$18,$00,$00,$06,$06,$00
				DB	$00,$30,$30,$00,$00,$00,$03
				DB	$80
				DB	$03,$80

				DB	$22,$00
				DB	$00,$00,$06,$06,$80
				DB	$30,$30,$80
				DB	$60,$60,$80
				DB	$80

				DB	$21,$03
				DB	$00,$00,$00,$00,$06,$06,$00
				DB	$30,$30,$80

				DB	$11,$26
				DB	$60,$60,$80

				DB	$FF

HH				USR	(TANDEM_TENTICLES)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$E0,$81,$02
				DB	$A2,$2E,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$16,$56,$CC,$16,$56,$3A
				DB	$CC,$FF,$DD,$01,$03,$0F
				DB	$FF

				DB	$22,$00			;tview dimens, offset
				DB	$07,$0C,$1C
				DB	$44,$3A,$7B
				DB	$3B
				DB	$70,$1C,$07
				DB	$03,$1D,$1E
				DB	$1D
				DB	$43,$06,$18
				DB	$00,$00,$00
				DB	$00
				DB	$63,$37,$1E
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

II				USR	(RUUIK'S_SOLDIER_)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$01
				DB	$AA,$2A,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$46,$CC,$28,$48,$CC
				DB	$2A,$4A,$CC,$37,$CC,$39
				DB	$DD,$02,$04,$06,$07,$08,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$70,$7E,$7F
				DB	$7F,$7E,$70
				DB	$0C
				DB	$07,$3F,$7F
				DB	$7F,$3F,$07
				DB	$18
				DB	$80
				DB	$18,$16,$06
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

JJ				USR	(WINGED_"BUG-EYE")-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$59,$82,$82
				DB	$AE,$3A,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E6,$CC,$EF,$DD,$01,$03
				DB	$FF

				DB	$42,$00			;tview dimens, offset
				DB	$70,$78,$1C
				DB	$06,$00,$00
				DB	$00
				DB	$00,$03,$0F
				DB	$3C,$58,$60
				DB	$70
				DB	$00,$40,$70
				DB	$3C,$1B,$07
				DB	$0E
				DB	$0E,$1F,$39
				DB	$60,$00,$00
				DB	$00
				DB	$80
				DB	$30,$6C,$00
				DB	$00,$00,$00
				DB	$00
				DB	$0C,$37,$00
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$FF				;tview end mark

KK				USR	("BLAST_CLAPPER"_)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$02
				DB	$A5,$29,$00
				DB	$00,$00,$00
				DB	$21,$03
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$46,$CC,$29,$38,$49
				DB	$DD,$02,$03,$FF

				DB	$21,$03			;tview dimens, offset
				DB	$70,$38,$58
				DB	$58,$3C,$6C
				DB	$0D
				DB	$07,$0E,$0D
				DB	$0D,$1E,$1B
				DB	$58
				DB	$FF				;tview end mark

LL				USR	("LOOP_HEAD"_____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$E1,$92,$12
				DB	$AE,$2E,$00
				DB	$00,$00,$00
				DB	$43,$12
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E7,$CC,$E8,$DD,$01,$02
				DB	$FF

				DB	$43,$12			;tview dimens, offset
				DB	$00,$60,$30
				DB	$58,$68,$58
				DB	$30
				DB	$7E,$7F,$00
				DB	$7F,$7F,$7F
				DB	$00
				DB	$1F,$7F,$00
				DB	$7F,$7F,$7F
				DB	$00
				DB	$00,$01,$03
				DB	$06,$0D,$0E
				DB	$0F
				DB	$60,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$7F,$5F,$07
				DB	$00,$10,$70
				DB	$7C
				DB	$7F,$3E,$38
				DB	$00,$00,$7F
				DB	$7F
				DB	$1F,$1E,$1C
				DB	$1C,$14,$7F
				DB	$01
				DB	$80
				DB	$7A,$20,$20
				DB	$00,$00,$00
				DB	$00
				DB	$03,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$FF				;tview end mark

MM				USR	(FLYING_SAUCER___)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$A2,$15,$00
				DB	$00,$00,$00
				DB	$43,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E7,$CC,$E9,$CC,$EA,$DD
				DB	$01,$02,$03,$FF

				DB	$43,$00
				DB	$00,$00,$60,$70,$78,$3C,$5C
				DB	$78,$7F,$07,$79,$7E,$7F,$3F
				DB	$1F,$7F,$60,$1F,$7F,$7F,$5C
				DB	$00,$01,$07,$0F,$1E,$3D,$3B
				DB	$5E,$6E,$6E,$6E,$6E,$6E,$5E
				DB	$0F,$07,$43,$73,$1B,$1B,$07
				DB	$20,$60,$73,$73,$73,$63,$23
				DB	$7B,$76,$76,$76,$76,$76,$7B
				DB	$5C,$3C,$78,$70,$60,$80
				DB	$3F,$7F,$7E,$79,$07,$7F,$78
				DB	$5C,$7F,$7F,$1F,$60,$7F,$1F
				DB	$3B,$3D,$1E,$0F,$07,$01,$00

				DB	$FF

NN				USR	(PHASE_WORM______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$40,$40,$30
				DB	$92,$09,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$47,$CC,$F9,$F8,$F7,$CC
				DB	$FE,$DD,$01,$03,$0F,$FF

				DB	animated+notcompiled+frame3
				DB	$12
				BYTE	special;special
				BYTE	repeat0;normalspeed

				DB	$11,$73
				DB	$28,$42,$01,$40,$21,$12,$00

				DB	$22,$01
				DB	$7C,$66,$66,$7C,$80
				DB	$01,$07,$2F,$1F,$5F,$1E,$21
				DB	$80
				DB	$04,$80

				DB	$22,$01
				DB	$78,$7E,$7E,$7F,$1F,$1F,$3E
				DB	$01,$07,$2F,$5F,$1F,$5E,$21
				DB	$3E,$7E,$66,$3C,$80
				DB	$12,$80

				DB	$23,$01
				DB	$78,$7E,$7E,$7F,$1F,$1F,$3E
				DB	$01,$07,$2F,$1F,$5F,$1E,$21
				DB	$3E,$3E,$3E,$9F
				DB	$04,$80
				DB	$3E,$3E,$7C,$7C,$78,$30,$00
				DB	$00,$00,$00,$00,$01,$80

				DB	$23,$01
				DB	$78,$7E,$7E,$7F,$1F,$1F,$3E
				DB	$01,$07,$2F,$5F,$1F,$5E,$21
				DB	$3E,$3E,$3E,$1F,$1F,$1F,$3E
				DB	$12,$00,$00,$00,$00,$00,$01
				DB	$7E,$7D,$38,$02,$48,$80
				DB	$00,$02,$00,$01,$80

				DB	$23,$01
				DB	$38,$7E,$7E,$3F,$1F,$1F,$3E
				DB	$80
				DB	$3E,$3E,$3E,$1F,$1F,$5F,$3E
				DB	$80
				DB	$7E,$7C,$3A,$00,$24,$80
				DB	$02,$00,$02,$80

				DB	$22,$0B
				DB	$1E,$33,$33,$3E,$7C,$7D,$38
				DB	$00,$00,$00,$01,$00,$02,$00
				DB	$02,$48,$80
				DB	$01,$80

				DB	$11,$00
				DB	$80

				DB	$FF

OO				USR	(ORGANISM_CLOUD__)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$1B,$08,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$CC,$36,$CC,$46,$CC
				DB	$F7,$F8,$DD,$01,$02,$03
				DB	$09,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$12,$18,$61
				DB	$26,$00,$46
				DB	$12
				DB	$26,$29,$08
				DB	$41,$08,$03
				DB	$69
				DB	$03,$48,$44
				DB	$00,$00,$00
				DB	$00
				DB	$10,$41,$0C
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

PP				USR	("HEXICLAW"______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$C9,$A4,$01
				DB	$AA,$2E,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E6,$CC,$EF,$DD,$01,$04
				DB	$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$00,$40
				DB	$38,$0C,$66
				DB	$6C
				DB	$7C,$0F,$4F
				DB	$7F,$73,$06
				DB	$2C
				DB	$3F,$71,$73
				DB	$7F,$4F,$60
				DB	$34
				DB	$00,$01,$03
				DB	$1D,$31,$66
				DB	$36
				DB	$64,$40,$40
				DB	$00,$00,$00
				DB	$00
				DB	$78,$01,$00
				DB	$00,$00,$00
				DB	$00
				DB	$1E,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$26,$03,$02
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

QQ				USR	(ACRUXITE________)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$01
				DB	$A2,$6E,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E6,$CC,$EF,$DD,$01,$03
				DB	$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$70,$70,$38
				DB	$38
				DB	$7C,$6C,$7C
				DB	$3D,$7D,$3C
				DB	$7C
				DB	$7F,$6F,$7F
				DB	$7B,$7F,$7B
				DB	$7F
				DB	$00,$00,$00
				DB	$1E,$1E,$38
				DB	$38
				DB	$58,$2C,$34
				DB	$00,$00,$00
				DB	$00
				DB	$6C,$7C,$01
				DB	$00,$00,$00
				DB	$00
				DB	$6F,$7F,$00
				DB	$00,$00,$00
				DB	$00
				DB	$34,$68,$5A
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

RR				USR	("FINGERS"_______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$D8,$8C,$22
				DB	$A9,$2A,$00
				DB	$00,$00,$00
				DB	$43,$10
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E7,$CC,$E8,$E9,$DD,$01
				DB	$02,$FF

				DB	$43,$10			;tview dimens, offset
				DB	$80
				DB	$00,$00,$00
				DB	$00,$60,$60
				DB	$70
				DB	$00,$00,$70
				DB	$1C,$6F,$6F
				DB	$1C
				DB	$00,$00,$03
				DB	$0E,$7D,$7D
				DB	$6E
				DB	$00,$0F,$38
				DB	$60,$7E,$43
				DB	$70
				DB	$70,$38,$38
				DB	$5D,$1F,$0F
				DB	$0E
				DB	$70,$00,$00
				DB	$1C,$36,$60
				DB	$60
				DB	$63,$60,$70
				DB	$30,$38,$1C
				DB	$0F
				DB	$5C,$46,$66
				DB	$66,$40,$30
				DB	$00
				DB	$0F,$0D,$0C
				DB	$06,$01,$03
				DB	$00
				DB	$43,$73,$5E
				DB	$40,$60,$3C
				DB	$00
				DB	$3F,$67,$6D
				DB	$6D,$0C,$06
				DB	$03
				DB	$FF				;tview end mark

SS				USR	(RIGELIAN_SNIPER_)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$01
				DB	$6A,$2E,$00
				DB	$00,$00,$00
				DB	$43,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$EE,$DD,$01,$FF

				DB	animated+notcompiled+frame1
				DB	$22
				BYTE	special;uparound
				BYTE	repeat0;normalspeed

				DB	$43,$00			;open hatch
				DB	$78,$08,$E8
				DB	$7F,$00,$FF
				DB	$7F,$00,$FF
				DB	$1F,$10,$97
				DB	$E8
				DB	$FF
				DB	$7F,$7F,$7F,$7E,$FF
				DB	$97
				DB	$08,$08,$78,$80
				DB	$00,$00,$7F,$80
				DB	$00,$60,$77,$68,$78,$90
				DB	$10,$10,$1E,$80

				DB	$43,$00			;closed hatch
				DB	$78,$08,$E8
				DB	$7F,$00,$FF
				DB	$7F,$00,$FF
				DB	$1F,$10,$97
				DB	$E8
				DB	$FF
				DB	$7F,$7F,$7F,$7E,$FF
				DB	$97
				DB	$68,$08,$78,$80
				DB	$7F,$00,$7F,$80
				DB	$7F,$00,$7F,$80
				DB	$17,$10,$1F,$80

				DB	$FF

TT				USR	("STINKY"________)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$19,$C8,$0B
				DB	$AA,$2E,$00
				DB	$00,$00,$00
				DB	$41,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E6,$CC,$EF,$DD,$01,$03
				DB	$FF

				DB	$41,$00			;tview dimens, offset
				DB	$00,$00,$78
				DB	$7C,$7C,$1E
				DB	$00
				DB	$38,$7F,$7F
				DB	$7F,$7F,$6F
				DB	$78
				DB	$1C,$7F,$7F
				DB	$7F,$7F,$76
				DB	$1F
				DB	$00,$01,$1F
				DB	$3F,$3F,$79
				DB	$00
				DB	$FF				;tview end mark

UU				USR	(PARTICLE_MAN____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$76,$09,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$F7,$CC,$FE,$DD,$01,$03
				DB	$FF

				DB	$23,$00			;tview dimens, offset
				DB	$10,$00,$24
				DB	$00,$48,$10
				DB	$00
				DB	$01,$00,$00
				DB	$04,$00,$05
				DB	$01
				DB	$20,$30,$68
				DB	$50,$78,$78
				DB	$7C
				DB	$08,$01,$04
				DB	$0D,$0E,$0F
				DB	$1F
				DB	$1C,$6E,$6F
				DB	$1B,$73,$03
				DB	$02
				DB	$1C,$3B,$7B
				DB	$6C,$67,$60
				DB	$20
				DB	$FF				;tview end mark

VV				USR	("BARACKADER"____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$02
				DB	$A9,$2A,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$27,$28,$CC,$37,$CC,$47
				DB	$48,$CC,$17,$18,$57,$58
				DB	$DD,$01,$02,$03,$05,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$00,$00,$0C
				DB	$18,$6E,$F0
				DB	$00,$00,$18
				DB	$0C,$3B,$87
				DB	$6E,$18,$0C
				DB	$80
				DB	$3B,$0C,$18
				DB	$80
				DB	$FF				;tview end mark

WW				USR	(PROBE_DROID_____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$A2,$9E,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E6,$DD,$01,$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$60
				DB	$00,$70,$78
				DB	$3C,$40,$7F
				DB	$41
				DB	$00,$77,$1B
				DB	$2C,$77,$7B
				DB	$7B
				DB	$00,$3F,$70
				DB	$00,$00,$00
				DB	$00
				DB	$38,$0E,$0C
				DB	$00,$00,$00
				DB	$00
				DB	$3C,$78,$70
				DB	$00,$00,$00
				DB	$00
				DB	$3C,$1F,$0F
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$FF				;tview end mark

XX				USR	(VEGAN_OFFICER___)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$03
				DB	$A3,$22,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$37,$CC,$FA,$DD,$01,$0F
				DB	$FF

				DB	$23,$00			;tview dimens, offset
				DB	$80
				DB	$00,$00,$00
				DB	$00,$00,$06
				DB	$03
				DB	$00,$73,$76
				DB	$06,$78,$7E
				DB	$7F
				DB	$20,$67,$67
				DB	$30,$0F,$3F
				DB	$7F
				DB	$3F,$7B,$73
				DB	$0B,$1A,$30
				DB	$00
				DB	$7E,$6F,$67
				DB	$68,$26,$06
				DB	$0C
				DB	$FF				;tview end mark

YY				USR	(ROBIEN_BRAIN____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$01
				DB	$A2,$69,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$16,$36,$56,$DD,$02,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$7C,$1C,$6C
				DB	$6C,$74,$18
				DB	$6C
				DB	$0F,$0E,$0D
				DB	$0D,$0D,$0E
				DB	$0F
				DB	$16,$0C,$18
				DB	$00,$00,$00
				DB	$00
				DB	$09,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

ZZ				USR	(????????????????)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$E0,$0C,$0A
				DB	$6B,$2D,$00
				DB	$00,$00,$00
				DB	$53,$01
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E7,$DD,$01,$FF

				DB	$53,$01			;tview dimens, offset
				DB	$30,$18,$6C
				DB	$3C,$0C,$2C
				DB	$2C
				DB	$00,$00,$00
				DB	$01,$61,$32
				DB	$5A
				DB	$00,$00,$00
				DB	$00,$19,$7E
				DB	$7F
				DB	$00,$00,$00
				DB	$38,$0F,$02
				DB	$01
				DB	$80
				DB	$5C,$38,$70
				DB	$7C,$0E,$1B
				DB	$23
				DB	$58,$39,$7B
				DB	$7B,$30,$6C
				DB	$1E
				DB	$7F,$7C,$7E
				DB	$73,$4E,$7F
				DB	$42
				DB	$01,$0D,$3B
				DB	$73,$61,$62
				DB	$64
				DB	$80
				DB	$44,$08,$50
				DB	$60,$30,$00
				DB	$00
				DB	$4E,$27,$0B
				DB	$06,$00,$00
				DB	$00
				DB	$80
				DB	$59,$62,$7A
				DB	$5C,$60,$60
				DB	$00
				DB	$01,$01,$01
				DB	$01,$00,$00
				DB	$00
				DB	$FF				;tview end mark

DATA_END_17
