MAGNETIC		USR	(MAGNETIC_SWEEPER)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$22
				BYTE	special;upstop
				BYTE	repeat0;normalspeed

				DB	$43,$00
				DB	$40,$38,$38,$58,$18,$D8
				DB	$13,$5B,$5B,$13,$00,$FB
				DB	$49,$5B,$5B,$49,$00,$DF
				DB	$03,$1D,$1D,$1B,$18,$9B
				DB	$58,$58,$18,$58,$58,$18,$60
				DB	$7B,$7B,$78,$7B,$7B,$7B,$7A
				DB	$5F,$5F,$1F,$5E,$DF
				DB	$1B,$1B,$18,$1B,$1B,$19,$06
				DB	$78,$78,$60,$00,$40,$80
				DB	$7A,$7A,$7A,$7B,$7B,$78,$00
				DB	$5F,$5F,$5F,$5F,$5F,$1F,$00
				DB	$1E,$1E,$06,$01,$03,$80

				DB	$43,$00
				DB	$40,$38,$38,$58,$18,$D8
				DB	$13,$5B,$5B,$13,$00,$FB
				DB	$49,$5B,$5B,$49,$00,$DF
				DB	$03,$1D,$1D,$1B,$18,$9B
				DB	$58,$58,$18,$58,$58,$18,$60
				DB	$7B,$7B,$78,$7B,$7B,$7B,$7A
				DB	$5F,$5F,$1F,$5E,$DF
				DB	$1B,$1B,$18,$1B,$1B,$19,$06
				DB	$78,$78,$60,$00,$40,$80
				DB	$0A,$6A,$1A,$7B,$7B,$78,$00
				DB	$58,$5B,$5B,$58,$5F,$1F,$00
				DB	$1E,$1E,$06,$01,$03,$80

				DB	$43,$00
				DB	$40,$38,$38,$58,$18,$D8
				DB	$13,$5B,$5B,$13,$00,$FB
				DB	$49,$5B,$5B,$49,$00,$5C,$5A
				DB	$03,$1D,$1D,$1B,$18,$9B
				DB	$58,$58,$18,$58,$58,$18,$60
				DB	$7B,$7B,$78,$7B,$7B,$7B,$7A
				DB	$52,$4E,$0E,$4C,$56,$51,$5F
				DB	$1B,$1B,$18,$1B,$1B,$19,$06
				DB	$78,$78,$60,$00,$40,$80
				DB	$0A,$6A,$1A,$7B,$7B,$78,$00
				DB	$58,$5B,$5B,$58,$5F,$1F,$00
				DB	$1E,$1E,$06,$01,$03,$80

				DB	$43,$00
				DB	$40,$38,$38,$58,$18,$D8
				DB	$13,$5B,$5B,$13,$00,$7B,$0B
				DB	$49,$5B,$5B,$49,$00,$5C,$5A
				DB	$03,$1D,$1D,$1B,$18,$9B
				DB	$58,$58,$18,$58,$58,$18,$60
				DB	$6B,$33,$48,$7B,$0B,$6B,$6A
				DB	$52,$4E,$0E,$4C,$56,$51,$5F
				DB	$1B,$1B,$18,$1B,$1B,$19,$06
				DB	$78,$78,$60,$00,$40,$80
				DB	$6A,$6A,$62,$3B,$43,$78,$00
				DB	$58,$5A,$5A,$58,$5F,$1F,$00
				DB	$1E,$1E,$06,$01,$03,$80

				DB	$FF

MISER			USR	("MISER"_________)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$12,$40
				DB	$09,$06,$0F
				DB	$16,$18,$38
				DB	$78,$78,$70
				DB	$80
				DB	$FF

EBKALEE			USR	(EBKAL'EE________)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$42,$00
				DB	$00,$00,$00
				DB	$7E,$7F,$7F
				DB	$40,$1C,$36
				DB	$60,$6D,$5B
				DB	$3B,$17,$38
				DB	$6C,$06,$76
				DB	$7B,$7D,$79
				DB	$00,$00,$00
				DB	$77,$6F,$77
				DB	$01,$00,$00
				DB	$00,$00,$01
				DB	$01,$00,$80
				DB	$60,$78,$40
				DB	$80,$07,$1F
				DB	$03,$80,$1E
				DB	$7F,$60,$80
				DB	$00,$00,$01
				DB	$80
				DB	$FF

SCREECHR		USR	("SCREECHER"_____)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$42,$17
				DB	$36,$1F,$3B
				DB	$3F,$73,$66
				DB	$5C,$00,$00
				DB	$00,$00,$00
				DB	$01,$73,$60
				DB	$40,$60,$60
				DB	$70,$38,$5C
				DB	$06,$0F,$0D
				DB	$0F,$0C,$06
				DB	$03,$70,$00
				DB	$60,$00,$40
				DB	$80,$7D,$7E
				DB	$7C,$73,$0D
				DB	$26,$20,$7B
				DB	$07,$33,$0C
				DB	$1B,$06,$00
				DB	$80
				DB	$FF

MAULER			USR	("MAULER"________)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$23,$00
				DB	$18,$33,$66
				DB	$76,$7C,$60
				DB	$30,$0C,$66
				DB	$33,$37,$1F
				DB	$03,$06,$53
				DB	$56,$36,$7C
				DB	$38,$5C,$36
				DB	$65,$35,$36
				DB	$1F,$0E,$1D
				DB	$36,$66,$33
				DB	$58,$4C,$0C
				DB	$18,$10,$33
				DB	$66,$0D,$19
				DB	$18,$0C,$04
				DB	$FF

MEMPLACR		USR	(MEM-PLACER_ROBOT)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$23,$00
				DB	$40,$60,$70
				DB	$38,$5C,$5E
				DB	$27,$01,$03
				DB	$07,$0E,$1D
				DB	$3D,$72,$7B
				DB	$27,$5F,$5E
				DB	$3D,$6D,$5B
				DB	$6F,$72,$7D
				DB	$3D,$5E,$5B
				DB	$6D,$5B,$33
				DB	$36,$66,$6C
				DB	$58,$40,$6D
				DB	$66,$36,$33
				DB	$1B,$0D,$01
				DB	$FF

SPARKLE			USR	(SPARKLE_________)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$21
				BYTE	blink;updown
				BYTE	repeat1;normalspeed

				DB	$42,$01
				DB	$00,$00,$00,$00,$32,$80
				DB	$00,$08,$10,$40,$77,$40,$10
				DB	$01,$10,$09,$03,$6F,$03,$09
				DB	$00,$00,$00,$00,$4D,$80
				DB	$80
				DB	$08,$80
				DB	$10,$01,$80
				DB	$80

				DB	$32,$31
				DB	$40,$00,$00,$00,$74,$80
				DB	$00,$03,$56,$7C,$7E,$7C,$56
				DB	$04,$03,$01,$00,$5D,$00,$01
				DB	$00,$40,$80
				DB	$03,$80
				DB	$03,$04,$80

				DB	$22,$61
				DB	$08,$30,$60,$40,$00,$40,$60
				DB	$40,$30,$1D,$0F,$07,$0F,$1D
				DB	$30,$08,$80
				DB	$30,$40,$80

				DB	$FF

ENCEPHAL		USR	(ENCEPHALOID_____)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$21,$01
				DB	$70,$1C,$6E
				DB	$77,$68,$1E
				DB	$70,$07,$1C
				DB	$3B,$77,$0B
				DB	$3C,$07
				DB	$FF

TRANSPER		USR	(TRANSPERENT_____)-	;THIS NAME IS SPELLED WRONG
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$21,$03
				DB	$70,$18,$6C
				DB	$5C,$3C,$6C
				DB	$0C,$07,$0C
				DB	$1B,$1D,$1E
				DB	$1B,$18
				DB	$FF

ACIDSPIT		USR	(ACID_SPITTER____)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$22,$00
				DB	$00,$60,$38
				DB	$5C,$5C,$DE
				DB	$00,$03,$0E
				DB	$1D,$1D,$BD
				DB	$3E,$76,$0E
				DB	$80,$3E,$37
				DB	$38,$80
				DB	$FF

ZETOC			USR	(ZETOC___________)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$42,$00
				DB	$30,$1C,$7E
				DB	$40,$00,$70
				DB	$18,$00,$60
				DB	$39,$7F,$1E
				DB	$7F,$0C,$60
				DB	$7F,$00,$0F
				DB	$78,$43,$03
				DB	$00,$00,$0C
				DB	$07,$00,$03
				DB	$3E,$18,$0C
				DB	$44,$80,$0C
				DB	$07,$01,$80
				DB	$0E,$18,$18
				DB	$80,$80
				DB	$FF

PHASOID			USR	(PHASOID_________)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$11
				BYTE	special;upstop
				BYTE	repeat0;normalspeed

				DB	$11,$00
				DB	$80
				DB	$80

				DB	$21,$03
				DB	$60,$30,$30,$18,$70,$80
				DB	$03,$06,$06,$0C,$07,$80

				DB	$22,$01
				DB	$60,$70,$78,$38,$38,$18,$70
				DB	$03,$07,$0F,$0E,$0E,$0C,$07
				DB	$60,$80
				DB	$03,$80

				DB	$22,$01
				DB	$60,$70,$7A,$3B,$3B,$1A,$70
				DB	$03,$07,$2F,$6E,$6E,$2C,$07
				DB	$60,$80
				DB	$03,$80

				DB	$FF

PSEUDOMO		USR	(PSEUDOMORT______)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$11
				BYTE	special;upstop
				BYTE	repeat0;normalspeed

				DB	$42,$00
				DB	$00,$60,$40,$40,$00,$60,$3E
				DB	$78,$41,$01,$1F,$78,$7F,$7C
				DB	$00,$7F,$78,$7F,$63,$75,$2D
				DB	$00,$00,$39,$7F,$5D,$3B,$1B
				DB	$40,$70,$1C,$80
				DB	$0F,$01,$80
				DB	$4C,$78,$80
				DB	$03,$80

				DB	$22,$00
				DB	$00,$40,$00,$70,$1C,$6E,$2E
				DB	$00,$01,$00,$07,$1C,$3B,$3A
				DB	$5E,$46,$16,$80
				DB	$1D,$01,$18,$80

				DB	$FF

TANGIBLE		USR	(TANGIBLE_GAS____)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$43,$20
				DB	$00,$40,$24
				DB	$52,$44,$12
				DB	$44,$00,$00
				DB	$02,$00,$02
				DB	$09,$12,$00
				DB	$10,$20,$10
				DB	$00,$00,$40
				DB	$00,$01,$04
				DB	$09,$02,$09
				DB	$05,$20,$00
				DB	$40,$60,$60
				DB	$B0,$68,$56
				DB	$57,$2F,$5E
				DB	$7E,$7C,$63
				DB	$7F,$1F,$07
				DB	$07,$07,$03
				DB	$01,$80,$28
				DB	$10,$24,$12
				DB	$08,$12,$09
				DB	$00,$12,$24
				DB	$02,$80,$14
				DB	$22,$08,$40
				DB	$28,$80,$80
				DB	$FF

PUDDLE			USR	(PUDDLE_CREATURE_)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$12
				BYTE	attack;updown ;is this sequence correct
				BYTE	repeat1;normalspeed

				DB	$52,$01
				DB	$00,$00,$60,$7C,$3E,$5F,$7F
				DB	$00,$47,$7F,$7F,$7F,$7E,$7F
				DB	$7C,$7F,$7F,$71,$60,$71,$7F
				DB	$00,$1F,$7F,$77,$6B,$7F,$3F
				DB	$00,$00,$00,$01,$01,$80
				DB	$7E,$7C,$80
				DB	$43,$80
				DB	$0F,$80
				DB	$0F,$80
				DB	$80

				DB	$51,$02
				DB	$00,$60,$7C,$3E,$5F,$7E,$78
				DB	$7E,$7F,$7F,$3F,$7E,$FF
				DB	$7F,$7F,$78,$70,$78,$FF
				DB	$0F,$7F,$77,$6B,$7F,$1F,$07
				DB	$00,$00,$01,$01,$80

				DB	$42,$01
				DB	$00,$00,$60,$78,$7C,$3C,$7C
				DB	$78,$7C,$7F,$3F,$1E,$3D,$7F
				DB	$00,$47,$7F,$7C,$78,$7C,$7F
				DB	$00,$0F,$3F,$7B,$75,$3F,$1F
				DB	$78,$80
				DB	$7F,$3E,$80
				DB	$7F,$70,$80
				DB	$07,$80

				DB	$FF

IONDIODE		USR	(ION_DIODE_ROBOT_)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$42,$10
				DB	$00,$00,$00
				DB	$00,$60,$7F
				DB	$63,$40,$60
				DB	$30,$58,$6D
				DB	$76,$6D,$00
				DB	$01,$03,$06
				DB	$6D,$5B,$6D
				DB	$00,$00,$00
				DB	$00,$01,$3F
				DB	$31,$03,$07
				DB	$03,$80,$58
				DB	$30,$60,$80
				DB	$06,$03,$01
				DB	$80,$30,$38
				DB	$30,$80
				DB	$FF

EXPLODER		USR	(VEGAN_EXPLODER__)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$11
				BYTE	attack;uparound
				BYTE	repeat0;normalspeed

				DB	$11,$42
				DB	$0C,$12,$21,$12,$0C,$80

				DB	$11,$42
				DB	$0C,$12,$33,$12,$0C,$80

				DB	$11,$42
				DB	$0C,$1E,$33,$1E,$0C,$80

				DB	$11,$42
				DB	$0C,$1E,$3F,$1E,$0C,$80

				DB	$FF

CARNIVOR		USR	(CARNIVORE_______)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+iscompiled+frame0
				DB	$12
				BYTE	blink;updown
				BYTE	repeat1;normalspeed

				DB	$23,$00
				DB	$00,$7C,$60,$C0
				DB	$00,$00,$03,$06,$05,$8D
				DB	$40,$60,$60,$70,$30,$3C,$3E
				DB	$0D,$0E,$0E,$0E,$0F,$1F,$3F
				DB	$3E,$5F,$6F,$6B,$5B,$33,$02
				DB	$3E,$7D,$7B,$6B,$6D,$66,$20

				DB	$22,$00
				DB	$40,$3C,$20,$00,$00,$A0
				DB	$01,$03,$00,$03,$00,$8B
				DB	$20,$10,$50,$40,$08,$C0
				DB	$0B,$08,$01,$01,$00,$81

				DB	$22,$00
				DB	$00,$20,$20,$10,$10,$D0
				DB	$00,$02,$02,$04,$04,$85
				DB	$50,$40,$48,$48,$C0
				DB	$05,$01,$09,$09,$81

				DB	$22,$00
				DB	$40,$60,$00,$60,$00,$E8
				DB	$01,$1E,$02,$00,$00,$82
				DB	$68,$08,$40,$40,$00,$C0
				DB	$02,$04,$05,$01,$08,$81

				DB	$FF

ATOMARRA		USR	(ATOM_ARRANGER___)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$22
				BYTE	special;uparound
				BYTE	repeat0;normalspeed

				DB	$43,$10
				DB	$00,$00,$40,$60,$60,$00,$60
				DB	$00,$00,$07,$79,$0E,$77,$7B
				DB	$38,$3E,$60,$1F,$78,$F7
				DB	$00,$00,$00,$00,$00,$07,$0F
				DB	$78,$3C,$1C,$1C,$38,$78,$30
				DB	$07,$7C,$00,$38,$40,$00,$07
				DB	$18,$0F,$00,$0D,$4F,$0E,$00
				DB	$7F,$0E,$1F,$0E,$0F,$3E,$07
				DB	$70,$70,$70,$60,$80
				DB	$0F,$0F,$0F,$07,$80
				DB	$00,$60,$40,$60,$60,$30,$10
				DB	$0F,$03,$03,$01,$80

				DB	$43,$01
				DB	$00,$60,$78,$3C,$0E,$7E,$07
				DB	$3E,$4F,$75,$1B,$6D,$76,$1B
				DB	$7C,$3F,$1C,$1B,$1D,$6E,$77
				DB	$1F,$30,$60,$60,$60,$30,$33
				DB	$03,$00,$40,$40,$40,$80
				DB	$67,$7F,$0F,$07,$07,$07,$37
				DB	$6B,$3C,$01,$00,$70,$1C,$06
				DB	$1B,$18,$18,$30,$31,$63,$66
				DB	$80
				DB	$4E,$78,$06,$06,$03,$80
				DB	$03,$1C,$70,$80
				DB	$66,$63,$01,$80

				DB	$43,$00
				DB	$00,$0E,$7E,$7C,$78,$60,$00
				DB	$00,$3E,$4F,$74,$1B,$6D,$76
				DB	$70,$7C,$3F,$1C,$1B,$1D,$2E
				DB	$07,$1F,$80
				DB	$80
				DB	$1B,$67,$7F,$0F,$87
				DB	$77,$6B,$7C,$01,$80
				DB	$00,$03,$03,$80
				DB	$00,$00,$40,$70,$7C,$7C,$78
				DB	$07,$07,$0F,$3F,$FF
				DB	$00,$00,$00,$00,$01,$01,$00
				DB	$80

				DB	$FF

LITTLMEN		USR	(LITTLE_MEN______)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	animated+notcompiled+frame0
				DB	$11
				BYTE	damage;upstop
				BYTE	repeat0;normalspeed

				DB	$22,$00
				DB	$00,$33,$00,$0C,$00,$33,$00
				DB	$18,$00,$60,$06,$00,$18,$00
				DB	$40,$00,$0C,$80
				DB	$61,$00,$06,$80

				DB	$22,$00
				DB	$00,$0C,$00,$00,$30,$00,$03
				DB	$06,$00,$60,$00,$18,$80
				DB	$00,$00,$30,$80
				DB	$06,$00,$60,$80

				DB	$21,$01
				DB	$30,$00,$00,$00,$03,$00,$40
				DB	$00,$60,$00,$00,$18,$00,$01

				DB	$22,$01
				DB	$0C,$80
				DB	$00,$00,$00,$00,$06,$80
				DB	$00,$30,$80
				DB	$80

				DB	$FF

BETEIGUE		USR	(BETEIGUESEN_____)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$22,$00
				DB	$FF
				DB	$70,$7C,$1E
				DB	$6F,$37,$6E
				DB	$5E,$03,$0F
				DB	$1C,$3B,$36
				DB	$37,$32,$78
				DB	$80,$11,$10
				DB	$10,$80
				DB	$FF

SHARPSHO		USR	("SHARP_SHOOTER"_)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$42,$00
				DB	$00,$00,$00
				DB	$00,$70,$38
				DB	$00,$00,$70
				DB	$1C,$60,$5F
				DB	$60,$1E,$00
				DB	$0F,$38,$07
				DB	$7B,$07,$78
				DB	$00,$00,$00
				DB	$00,$0F,$1C
				DB	$00,$80,$76
				DB	$06,$04,$80
				DB	$6F,$60,$20
				DB	$80,$80
				DB	$FF

TRIPEDIV		USR	(TRIPED_IV_ROBOT_)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$43,$23
				DB	$60,$40,$80
				DB	$01,$03,$0F
				DB	$4F,$76,$38
				DB	$40,$00,$00
				DB	$60,$67,$5F
				DB	$38,$77,$0E
				DB	$07,$03,$03
				DB	$01,$80,$7C
				DB	$7C,$0C,$0C
				DB	$0C,$00,$0C
				DB	$5F,$5F,$20
				DB	$70,$40,$20
				DB	$40,$46,$37
				DB	$78,$67,$07
				DB	$08,$07,$00
				DB	$00,$01,$07
				DB	$1E,$78,$30
				DB	$80,$80,$03
				DB	$03,$03,$80
				DB	$18,$0C,$06
				DB	$03,$80
				DB	$FF

PARASITE		USR	(WEBBED_PARASITE_)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$22,$00
				DB	$00,$30,$58
				DB	$7C,$5E,$76
				DB	$06,$00,$07
				DB	$0D,$1E,$3D
				DB	$37,$30,$06
				DB	$0C,$0C,$80
				DB	$30,$18,$18
				DB	$80
				DB	$FF

WORKER			USR	(WORKER_INSECT___)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$23,$00
				DB	$00,$00,$40
				DB	$60,$5E,$E0
				DB	$00,$00,$01
				DB	$03,$3D,$83
				DB	$60,$5E,$60
				DB	$70,$70,$6F
				DB	$70,$03,$3D
				DB	$03,$07,$07
				DB	$7B,$07,$70
				DB	$10,$6E,$36
				DB	$66,$86,$07
				DB	$04,$3B,$66
				DB	$63,$40,$00
				DB	$FF

FIGHTER			USR	(FIGHTER_INSECT__)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$23,$00
				DB	$00,$00,$40
				DB	$60,$5E,$E0
				DB	$00,$00,$01
				DB	$03,$3D,$83
				DB	$60,$5E,$60
				DB	$70,$70,$6F
				DB	$70,$03,$3D
				DB	$03,$07,$07
				DB	$7B,$07,$70
				DB	$10,$6E,$36
				DB	$66,$86,$07
				DB	$04,$3B,$66
				DB	$63,$40,$00
				DB	$FF

OKKARMAR		USR	(OKKAR_MARSUPIAL_)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$22,$00
				DB	$01,$03,$4E
				DB	$74,$78,$38
				DB	$6C,$04,$03
				DB	$01,$01,$73
				DB	$1F,$01,$0C
				DB	$0C,$08,$80
				DB	$80
				DB	$FF

OKKARPLA		USR	(OKKAR_PLANT_____)-
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$FF,$DD,$19,$FF	;temporary

				DB	$23,$00
				DB	$60,$40,$40
				DB	$00,$00,$00
				DB	$01,$00,$41
				DB	$71,$3B,$1F
				DB	$0E,$06,$07
				DB	$1E,$38,$70
				DB	$7E,$4F,$31
				DB	$07,$07,$07
				DB	$03,$1B,$77
				DB	$47,$78,$38
				DB	$1C,$1C,$36
				DB	$36,$60,$0E
				DB	$1C,$38,$70
				DB	$40,$80
				DB	$FF

DATA_END_13
