A				USR	(SPACE_MAN_______)-
				DB	$16,$15,$00
				DB	$00,$00,$10
				DB	$05,$00,$00
				DB	$00,$00,$00
				DB	$60,$00,$00
				DB	$00,$00,$18
				DB	$E1,$1C,$03
				DB	$A5,$2B,$80
				DB	$40,$38,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$CC,$48,$CC,$EF,$DD
				DB	$01,$02,$0F,$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$40,$40
				DB	$40,$04,$7C
				DB	$00
				DB	$00,$00,$61
				DB	$71,$70,$77
				DB	$50
				DB	$00,$00,$07
				DB	$0F,$0F,$6F
				DB	$0B
				DB	$00,$02,$03
				DB	$03,$20,$3B
				DB	$03
				DB	$40,$40,$40
				DB	$00,$00,$00
				DB	$00
				DB	$31,$61,$00
				DB	$00,$00,$00
				DB	$00
				DB	$0C,$07,$00
				DB	$00,$00,$00
				DB	$00
				DB	$03,$03,$02
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

B				USR	("AIR_SWIMMER"___)-
				DB	$18,$20,$10
				DB	$00,$00,$09
				DB	$15,$00,$00
				DB	$00,$00,$00
				DB	$45,$00,$00
				DB	$00,$00,$10
				DB	$00,$00,$02
				DB	$AB,$1A,$4A
				DB	$70,$E0,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$DD,$01,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$00,$40,$00
				DB	$60,$78,$5C
				DB	$7C
				DB	$03,$03,$00
				DB	$07,$1F,$3B
				DB	$3F
				DB	$0C,$0C,$08
				DB	$00,$00,$00
				DB	$00
				DB	$30,$30,$10
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

C				USR	(SHIELDED_OOMAR__)-
				DB	$20,$19,$15
				DB	$00,$00,$16
				DB	$06,$00,$00
				DB	$00,$00,$00
				DB	$40,$00,$00
				DB	$00,$00,$10
				DB	$00,$00,$03
				DB	$A9,$2D,$40
				DB	$00,$C0,$01
				DB	$21,$02
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$39,$CC,$2A,$4A
				DB	$DD,$01,$02,$04,$FF

				DB	$21,$02			;tview dimens, offset
				DB	$78,$0C,$1C
				DB	$78,$00,$7C
				DB	$00
				DB	$03,$06,$0F
				DB	$1B,$18,$07
				DB	$00
				DB	$FF				;tview end mark

D				USR	(MONOPTIC_HOPPER_)-
				DB	$26,$24,$00
				DB	$00,$00,$09
				DB	$10,$00,$00
				DB	$00,$00,$00
				DB	$75,$00,$00
				DB	$00,$00,$18
				DB	$E9,$A4,$02
				DB	$AF,$2E,$80
				DB	$18,$28,$00
				DB	$52,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$EF,$DD,$01,$02
				DB	$FF

				DB	$52,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$0C,$6D
				DB	$18
				DB	$00,$00,$00
				DB	$78,$7E,$63
				DB	$6C
				DB	$00,$00,$40
				DB	$6F,$37,$47
				DB	$7F
				DB	$06,$0F,$19
				DB	$70,$00,$7F
				DB	$00
				DB	$00,$00,$00
				DB	$01,$00,$01
				DB	$00
				DB	$30,$60,$40
				DB	$00,$00,$00
				DB	$00
				DB	$06,$03,$01
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$80
				DB	$80
				DB	$FF				;tview end mark

E				USR	(MPC3_ROBOT______)-
				DB	$21,$16,$00
				DB	$00,$00,$04
				DB	$08,$00,$00
				DB	$00,$00,$00
				DB	$60,$00,$00
				DB	$00,$00,$18
				DB	$C0,$2C,$00
				DB	$AA,$AE,$80
				DB	$28,$00,$00
				DB	$52,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$16,$CC,$28,$3A,$DD,$01
				DB	$03,$FF

				DB	$52,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$00,$70
				DB	$5C
				DB	$60,$70,$18
				DB	$7C,$78,$30
				DB	$6B
				DB	$07,$0F,$1F
				DB	$33,$1F,$0E
				DB	$57
				DB	$00,$00,$00
				DB	$00,$00,$0E
				DB	$3B
				DB	$80
				DB	$0E,$1B,$33
				DB	$00,$00,$00
				DB	$00
				DB	$1E,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$78,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$70,$58,$4C
				DB	$00,$00,$00
				DB	$00
				DB	$00,$01,$01
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

F				USR	("FROWNER"_______)-
				DB	$15,$15,$00
				DB	$00,$00,$08
				DB	$09,$00,$00
				DB	$00,$00,$00
				DB	$70,$00,$00
				DB	$00,$00,$98
				DB	$41,$C2,$03
				DB	$AE,$2A,$80
				DB	$28,$00,$00
				DB	$51,$03
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$EF,$DD,$01,$02
				DB	$FF

				DB	$51,$03			;tview dimens, offset
				DB	$7E,$7F,$7E
				DB	$00,$00,$00
				DB	$00
				DB	$00,$71,$0E
				DB	$78,$40,$30
				DB	$60
				DB	$00,$0F,$71
				DB	$1E,$03,$0C
				DB	$07
				DB	$7E,$7F,$7E
				DB	$00,$00,$00
				DB	$00
				DB	$00,$01,$00
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

G				USR	(MEERN_MUTATION__)-
				DB	$11,$10,$00
				DB	$00,$00,$10
				DB	$08,$00,$00
				DB	$00,$00,$00
				DB	$75,$00,$00
				DB	$00,$00,$18
				DB	$41,$E2,$11
				DB	$AA,$2E,$80
				DB	$10,$28,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$46,$CC,$17,$CC,$EF,$DD
				DB	$01,$02,$0F,$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$7E,$06,$06
				DB	$46
				DB	$70,$7C,$0E
				DB	$73,$3C,$4F
				DB	$07
				DB	$07,$1F,$7C
				DB	$7B,$3C,$07
				DB	$18
				DB	$00,$00,$00
				DB	$07,$0E,$18
				DB	$30
				DB	$46,$4C,$18
				DB	$00,$00,$00
				DB	$00
				DB	$05,$01,$03
				DB	$00,$00,$00
				DB	$00
				DB	$18,$00,$40
				DB	$00,$00,$00
				DB	$00
				DB	$3E,$03,$01
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

H				USR	(BURROWING_TAAN__)-
				DB	$20,$16,$00
				DB	$00,$00,$08
				DB	$14,$00,$00
				DB	$00,$00,$00
				DB	$60,$00,$00
				DB	$00,$00,$BC
				DB	$63,$CC,$02
				DB	$AA,$2B,$80
				DB	$40,$00,$00
				DB	$43,$10
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$27,$37,$47,$DD,$01,$FF

				DB	$43,$10			;tview dimens, offset
				DB	$00,$78,$0E
				DB	$03,$03,$03
				DB	$46
				DB	$00,$67,$38
				DB	$4C,$06,$03
				DB	$01
				DB	$7E,$03,$00
				DB	$03,$0E,$38
				DB	$60
				DB	$07,$1C,$30
				DB	$60,$60,$60
				DB	$30
				DB	$46,$6C,$68
				DB	$60,$40,$40
				DB	$00
				DB	$01,$70,$6C
				DB	$2E,$6D,$71
				DB	$03
				DB	$40,$03,$4D
				DB	$7D,$0D,$03
				DB	$00
				DB	$1B,$0C,$07
				DB	$18,$30,$30
				DB	$30
				DB	$38,$6C,$4C
				DB	$38,$60,$00
				DB	$00
				DB	$0E,$18,$19
				DB	$0E,$03,$00
				DB	$03
				DB	$80
				DB	$18,$0C,$06
				DB	$06,$03,$03
				DB	$03
				DB	$FF				;tview end mark

I				USR	(ROBOTROID_______)-
				DB	$17,$17,$10
				DB	$00,$00,$05
				DB	$09,$00,$00
				DB	$00,$00,$00
				DB	$65,$00,$00
				DB	$00,$00,$10
				DB	$00,$00,$00
				DB	$A6,$EE,$4A
				DB	$68,$40,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$46,$CC,$17,$57,$DD
				DB	$02,$04,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$00,$78,$18
				DB	$4F,$69,$69
				DB	$0F
				DB	$00,$0F,$0C
				DB	$79,$4B,$4B
				DB	$78
				DB	$78,$78,$38
				DB	$00,$00,$00
				DB	$00
				DB	$0F,$0F,$0E
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

J				USR	(JUNGLE_SWINGER__)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$D9,$80,$83
				DB	$AA,$2A,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$28,$48,$CC,$38
				DB	$DD,$01,$03,$0F,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$40,$60
				DB	$60
				DB	$00,$60,$30
				DB	$18,$0F,$0C
				DB	$07
				DB	$30,$18,$0C
				DB	$00,$00,$00
				DB	$00
				DB	$18,$03,$00
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

K				USR	(ROLLER_ALIEN____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$80,$00,$01
				DB	$A2,$2E,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$46,$CC,$17,$48,$19,$DD
				DB	$01,$02,$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$0E,$7E
				DB	$0E
				DB	$00,$60,$78
				DB	$1C,$60,$7F
				DB	$60
				DB	$00,$07,$1F
				DB	$38,$07,$7F
				DB	$07
				DB	$00,$00,$00
				DB	$00,$70,$7F
				DB	$70
				DB	$80
				DB	$1C,$78,$60
				DB	$00,$00,$00
				DB	$00
				DB	$38,$1F,$07
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$FF				;tview end mark

L				USR	(NUNKI_STARBEAST_)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$F9,$80,$2A
				DB	$A5,$2A,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$56,$CC,$16,$27,$37,$47
				DB	$18,$58,$DD,$01,$03,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$60,$70,$38
				DB	$58,$5C,$5E
				DB	$36
				DB	$06,$0F,$1C
				DB	$1B,$3B,$7B
				DB	$6C
				DB	$76,$6E,$1A
				DB	$00,$00,$00
				DB	$00
				DB	$6F,$76,$58
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

M				USR	(ELATION_TRAITOR_)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$F9,$90,$12
				DB	$AA,$2E,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$CC,$17,$3A,$59,$DD
				DB	$01,$03,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$70,$7C,$7C
				DB	$0E,$76,$74
				DB	$70
				DB	$03,$0F,$0F
				DB	$1C,$1B,$0B
				DB	$03
				DB	$30,$18,$18
				DB	$00,$00,$00
				DB	$00
				DB	$03,$03,$03
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

N				USR	(UNKNOWN_PLANT___)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$E1,$8C,$00
				DB	$93,$2D,$00
				DB	$00,$00,$00
				DB	$53,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$17,$27,$CC,$38,$48,$DD
				DB	$01,$02,$FF

				DB	$53,$00			;tview dimens, offset
				DB	$06,$4C,$78
				DB	$30,$3C,$0E
				DB	$07
				DB	$1C,$37,$00
				DB	$60,$33,$06
				DB	$78
				DB	$30,$73,$33
				DB	$19,$0C,$70
				DB	$6F
				DB	$03,$19,$18
				DB	$0C,$00,$67
				DB	$1F
				DB	$80
				DB	$7F,$7C,$60
				DB	$00,$78,$00
				DB	$40
				DB	$7C,$7B,$7B
				DB	$7C,$7D,$7C
				DB	$7B
				DB	$5F,$3F,$7F
				DB	$7E,$7F,$7F
				DB	$3F
				DB	$3D,$70,$76
				DB	$70,$6E,$60
				DB	$63
				DB	$00,$00,$00
				DB	$00,$01,$01
				DB	$01
				DB	$7E,$30,$18
				DB	$18,$0C,$00
				DB	$00
				DB	$78,$70,$0E
				DB	$00,$03,$7E
				DB	$00
				DB	$1F,$61,$66
				DB	$03,$7C,$07
				DB	$00
				DB	$6E,$70,$7C
				DB	$77,$61,$60
				DB	$7E
				DB	$01,$00,$00
				DB	$00,$00,$01
				DB	$00
				DB	$FF				;tview end mark

O				USR	(ROLLER_ALIEN____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$80,$00,$01
				DB	$A2,$2E,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$46,$CC,$17,$48,$19,$DD
				DB	$01,$02,$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$0E,$7E
				DB	$0E
				DB	$00,$60,$78
				DB	$1C,$60,$7F
				DB	$60
				DB	$00,$07,$1F
				DB	$38,$07,$7F
				DB	$07
				DB	$00,$00,$00
				DB	$00,$70,$7F
				DB	$70
				DB	$80
				DB	$1C,$78,$60
				DB	$00,$00,$00
				DB	$00
				DB	$38,$1F,$07
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$FF				;tview end mark

P				USR	(FROBOT__________)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$A6,$EF,$00
				DB	$00,$00,$00
				DB	$22,$01
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$27,$47,$18,$58
				DB	$29,$39,$49,$2A,$4A,$DD
				DB	$01,$07,$FF

				DB	$22,$01			;tview dimens, offset
				DB	$00,$00,$40
				DB	$60,$60,$58
				DB	$0C
				DB	$00,$03,$03
				DB	$03,$03,$03
				DB	$00
				DB	$80
				DB	$03,$03,$00
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

Q				USR	("TWISTER"_______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$40,$81,$02
				DB	$AA,$2A,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$2A,$4A,$CC,$39
				DB	$DD,$01,$03,$0F,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$04,$08,$50
				DB	$70,$1C,$77
				DB	$70
				DB	$11,$09,$05
				DB	$07,$77,$1C
				DB	$07
				DB	$50,$48,$44
				DB	$00,$00,$00
				DB	$00
				DB	$05,$08,$10
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

R				USR	("BARACKADE"_____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$02
				DB	$A9,$2A,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$27,$28,$CC,$37,$CC,$47
				DB	$48,$CC,$17,$18,$57,$58
				DB	$DD,$01,$02,$03,$05,$FF

				DB	animated+notcompiled+frame0
				DB	$11
				BYTE	damage;upstop
				BYTE	repeat0;normalspeed

				DB	$31,$02
				DB	$7F,$7F,$7F,$7F,$80
				DB	$7F,$7F,$7F,$7F,$80
				DB	$01,$01,$01,$01,$80

				DB	$31,$02
				DB	$7F,$7F,$73,$4F,$80
				DB	$7F,$7F,$7D,$7C,$80
				DB	$01,$01,$01,$01,$80

				DB	$31,$02
				DB	$7F,$37,$65,$40,$80
				DB	$7E,$3F,$0D,$0C,$80
				DB	$01,$01,$80

				DB	$31,$02
				DB	$0D,$37,$04,$40,$80
				DB	$72,$20,$0D,$08,$80
				DB	$01,$80

				DB	$FF

S				USR	(PHASE_WORM______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$40,$40,$30
				DB	$93,$09,$00
				DB	$00,$00,$00
				DB	$23,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$F7,$CC,$FE,$DD,$01,$06
				DB	$FF

				DB	animated+notcompiled+frame3
				DB	$12
				BYTE	special;special
				BYTE	repeat0;normalspeed

				DB	$11,$73
				DB	$28,$42,$01,$40,$21,$12,$00

				DB	$22,$01
				DB	$7C,$66,$66,$7C,$80
				DB	$01,$07,$2F,$1F,$5F,$1E,$21
				DB	$80
				DB	$04,$80

				DB	$22,$01
				DB	$78,$7E,$7E,$7F,$1F,$1F,$3E
				DB	$01,$07,$2F,$5F,$1F,$5E,$21
				DB	$3E,$7E,$66,$3C,$80
				DB	$12,$80

				DB	$23,$01
				DB	$78,$7E,$7E,$7F,$1F,$1F,$3E
				DB	$01,$07,$2F,$1F,$5F,$1E,$21
				DB	$3E,$3E,$3E,$9F
				DB	$04,$80
				DB	$3E,$3E,$7C,$7C,$78,$30,$00
				DB	$00,$00,$00,$00,$01,$80

				DB	$23,$01
				DB	$78,$7E,$7E,$7F,$1F,$1F,$3E
				DB	$01,$07,$2F,$5F,$1F,$5E,$21
				DB	$3E,$3E,$3E,$1F,$1F,$1F,$3E
				DB	$12,$00,$00,$00,$00,$00,$01
				DB	$7E,$7D,$38,$02,$48,$80
				DB	$00,$02,$00,$01,$80

				DB	$23,$01
				DB	$38,$7E,$7E,$3F,$1F,$1F,$3E
				DB	$80
				DB	$3E,$3E,$3E,$1F,$1F,$5F,$3E
				DB	$80
				DB	$7E,$7C,$3A,$00,$24,$80
				DB	$02,$00,$02,$80

				DB	$22,$0B
				DB	$1E,$33,$33,$3E,$7C,$7D,$38
				DB	$00,$00,$00,$01,$00,$02,$00
				DB	$02,$48,$80
				DB	$01,$80

				DB	$11,$00
				DB	$80

				DB	$FF

T				USR	(PROBE_DROID_____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$A2,$9E,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E6,$DD,$01,$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$60
				DB	$00,$70,$78
				DB	$3C,$40,$7F
				DB	$41
				DB	$00,$77,$1B
				DB	$2C,$77,$7B
				DB	$7B
				DB	$00,$3F,$70
				DB	$00,$00,$00
				DB	$00
				DB	$38,$0E,$0C
				DB	$00,$00,$00
				DB	$00
				DB	$3C,$78,$70
				DB	$00,$00,$00
				DB	$00
				DB	$3C,$1F,$0F
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$FF				;tview end mark

U				USR	(ARMORED_ALIEN___)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$01,$80,$00
				DB	$A1,$2D,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$F6,$CC,$F7,$DD,$02,$04
				DB	$FF

				DB	$22,$00			;tview dimens, offset
				DB	$60,$78,$78
				DB	$7C,$7C,$7C
				DB	$78
				DB	$03,$0F,$0F
				DB	$1F,$1F,$1F
				DB	$0F
				DB	$78,$60,$00
				DB	$00,$00,$00
				DB	$00
				DB	$0F,$03,$00
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

V				USR	(GRUNTER_PACK_DOG)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$19,$C0,$3B
				DB	$AB,$26,$00
				DB	$00,$00,$00
				DB	$22,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$27,$47,$37,$DD
				DB	$01,$03,$FF

				DB	$22,$00			;tview dimens, offset
				DB	$00,$60,$70
				DB	$70,$70,$70
				DB	$70
				DB	$00,$03,$07
				DB	$07,$07,$07
				DB	$07
				DB	$0F,$78,$60
				DB	$00,$00,$00
				DB	$00
				DB	$78,$0F,$03
				DB	$00,$00,$00
				DB	$00
				DB	$FF				;tview end mark

W				USR	("DRAGON_FLY"____)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$01
				DB	$AE,$1A,$00
				DB	$00,$00,$00
				DB	$42,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$26,$CC,$37,$47,$28,$DD
				DB	$01,$02,$FF

				DB	$42,$00			;tview dimens, offset
				DB	$00,$3E,$70
				DB	$00,$00,$00
				DB	$00
				DB	$00,$00,$07
				DB	$3E,$78,$5C
				DB	$36
				DB	$00,$00,$60
				DB	$7C,$1F,$3B
				DB	$6C
				DB	$00,$7C,$0F
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$6E,$78,$00
				DB	$00,$00,$00
				DB	$00
				DB	$76,$1F,$00
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$FF				;tview end mark

X				USR	("SQUINTER"______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$F5,$D4,$02
				DB	$A1,$2A,$00
				DB	$00,$00,$00
				DB	$41,$03
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$36,$CC,$17,$19,$39,$2A
				DB	$DD,$01,$03,$FF

				DB	$41,$03			;tview dimens, offset
				DB	$00,$70,$78
				DB	$70,$00,$00
				DB	$00
				DB	$40,$77,$6F
				DB	$77,$40,$00
				DB	$00
				DB	$03,$6F,$77
				DB	$6F,$03,$00
				DB	$00
				DB	$00,$0F,$1F
				DB	$0F,$00,$00
				DB	$00
				DB	$FF				;tview end mark

Y				USR	(BETA_CENTAURIAN_)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$02
				DB	$AA,$16,$00
				DB	$00,$00,$00
				DB	$43,$00
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E7,$CC,$EA,$DD,$01,$02
				DB	$FF

				DB	$43,$00			;tview dimens, offset
				DB	$00,$00,$00
				DB	$40,$60,$30
				DB	$58
				DB	$00,$70,$1E
				DB	$63,$7C,$1F
				DB	$6F
				DB	$00,$0F,$78
				DB	$47,$3F,$78
				DB	$77
				DB	$00,$00,$00
				DB	$03,$06,$0D
				DB	$1B
				DB	$58,$6C,$6C
				DB	$6C,$6C,$6C
				DB	$58
				DB	$33,$5D,$5E
				DB	$5E,$36,$76
				DB	$65
				DB	$4C,$3B,$7B
				DB	$7A,$6C,$6F
				DB	$26
				DB	$1B,$37,$36
				DB	$36,$36,$36
				DB	$1B
				DB	$58,$30,$60
				DB	$40,$00,$00
				DB	$00
				DB	$1B,$7F,$7C
				DB	$63,$1E,$70
				DB	$00
				DB	$59,$7F,$3F
				DB	$47,$78,$0F
				DB	$00
				DB	$1B,$0D,$06
				DB	$03,$00,$00
				DB	$00
				DB	$FF				;tview end mark

Z				USR	(LANTHOSER_______)-
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$00,$00,$00
				DB	$E1,$D0,$32
				DB	$AA,$2E,$00
				DB	$00,$00,$00
				DB	$52,$01
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE,$EE,$EE
				DB	$EE

				DB	$E6,$DD,$01,$FF

				DB	$52,$01			;tview dimens, offset
				DB	$00,$7E,$7F
				DB	$3F,$7F,$7E
				DB	$60
				DB	$5F,$67,$39
				DB	$3E,$39,$67
				DB	$5F
				DB	$7B,$66,$1C
				DB	$7C,$1C,$66
				DB	$7B
				DB	$01,$7F,$7F
				DB	$7C,$7F,$7F
				DB	$07
				DB	$00,$00,$01
				DB	$01,$01,$00
				DB	$00
				DB	$80
				DB	$3C,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$3C,$00,$00
				DB	$00,$00,$00
				DB	$00
				DB	$80
				DB	$80
				DB	$FF				;tview end mark

